framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session:
        cookie_secure: true
        cookie_httponly: true
        enabled: true
        handler_id: null
        cookie_samesite: 'none'  # 'Strict' ou 'None' sont également possibles
        cookie_lifetime: 3600  # Durée de vie du cookie (en secondes)
    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
