nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin:
            - 'https://cg-animalia.vercel.app'
        allow_headers:
            - 'content-type'
            - 'authorization'
        allow_methods:
            - 'GET'
            - 'POST'
            - 'OPTIONS'
            - 'PUT'
            - 'DELETE'
        max_age: 3600
    paths:
        '^/':
            allow_origin:
                - 'https://cg-animalia.vercel.app'
            allow_headers:
                - 'content-type'
                - 'authorization'
            allow_methods:
                - 'GET'
                - 'POST'
                - 'OPTIONS'
                - 'PUT'
                - 'DELETE'
            max_age: 3600
            allow_credentials: true
