security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\SimpleAuthenticator
            entry_point: App\Security\CustomAuthenticationEntryPoint  # Point d'entrée personnalisé
            logout:
                path: app_logout

            # Configuration "Remember Me" avec les options cookies
            remember_me:
                secret: '%env(APP_SECRET)%'
                secure: auto     # Activer 'secure' pour les cookies en HTTPS
                samesite: lax    # Configure SameSite à 'Lax' (peut être 'Strict' ou 'None')
                httponly: true   # Rend les cookies HTTP-only pour éviter les accès JavaScript
                lifetime: 3600   # Durée de vie du cookie en secondes (1 heure ici)

    access_control:
        # Exemples de contrôle d'accès
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/dashboard, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_EMPLOYE:       ROLE_EMPLOYE
        ROLE_SUPER_ADMIN: ROLE_ADMIN

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
