controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_page:
    path: /admin
    controller: App\Controller\AdminController::index
    methods: GET

